### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by schemar**

### CODE REVIEW

**Review by 0xsarvesh — APPROVED** [review]
LGTM 
Should this be added?
https://github.com/OpenSTFoundation/mosaic.js/pull/124

**Comment by schemar** [comment]
> 
> 
> LGTM
> Should this be added?
> #124

I was thinking about it 🤔 It is not merged *yet* ...

**Comment by 0xsarvesh** [comment]
> > LGTM
> > Should this be added?
> > #124
> 
> I was thinking about it 🤔 It is not merged _yet_ ...

is it mergeable?  
This is done because it was requested by the Kit team.

**Comment by schemar** [comment]
> 
> 
> > > LGTM
> > > Should this be added?
> > > #124
> > 
> > 
> > I was thinking about it 🤔 It is not merged _yet_ ...
> 
> is it mergeable?
> This is done because it was requested by the Kit team.

Merged and added to changelog

**Pull request merged**
