### PR TITLE
Facilitator.stake now returns nonce and msg hash

### LINKED ISSUE #136: In Facilitator, stake function should return message hash and staker nonce
Currently, `stake` function in the facilitator returns receipt. Along with the receipt, it should return the `message hash` and `nonce` as well. This message hash and nonce is needed in the next step where the consumer will call `progressStake`

### PR DESCRIPTION
**Pull request by schemar**
`Facilitator.stake()` now returns nonce and message hash. The events
are part of the web3 PromiEvent response and can be easily parsed from
the return object.

Refactored Facilitator. The stake function was too verbose. I extracted
some methods out to make the stake function more readable.

Updated integration tests to use different value token and base token.
Doing this also revealed the bug in the StakeHelper. The integration
tests now deploy two separate EIP20 tokens for base token and value
token. Those are now set on the Gateway and CoGateway as baes token and
value token.

The EIP20Gateway contract interact did not catch the case where the
possible reward is higher than the stake amount and the contract
reverts. I added the check as part of this ticket as it was a difficult
to track issue I faced with integration tests.

Added unit tests for facilitator and gateway. The facilitator stake unit
test now includes the response of nonce and message hash. The gateway
stake unit test now includes the check for the amount to be greater than
gas price times gas limit.

Added integration test for facilitator. I created a new file in the
integration test directory and let the facilitator stake with the
gateways that were deployd as part of the setup module integration test.
Because of the proper token setup on the gateways, I had to add a line
to the stake helper functional test where I set the value token (ref. #137)

Various linting errors fixed.

Fixes #136

### CODE REVIEW

**Comment by 0xsarvesh** [comment]
> `Facilitator.stake()` now returns nonce and message hash. The events
> are part of the web3 PromiEvent response and can be easily parsed from
> the return object.
> 
> Refactored Facilitator. The stake function was too verbose. I extracted
> some methods out to make the stake function more readable.
> 
> Updated integration tests to use different value token and base token.
> Doing this also revealed the bug in the StakeHelper. The integration
> tests now deploy two separate EIP20 tokens for base token and value
> token. Those are now set on the Gateway and CoGateway as baes token and
> value token.
> 
> The EIP20Gateway contract interact did not catch the case where the
> possible reward is higher than the stake amount and the contract
> reverts. I added the check as part of this ticket as it was a difficult
> to track issue I faced with integration tests.
> 
> Added unit tests for facilitator and gateway. The facilitator stake unit
> test now includes the response of nonce and message hash. The gateway
> stake unit test now includes the check for the amount to be greater than
> gas price times gas limit.
> 
> Added integration test for facilitator. I created a new file in the
> integration test directory and let the facilitator stake with the
> gateways that were deployd as part of the setup module integration test.
> Because of the proper token setup on the gateways, I had to add a line
> to the stake helper functional test where I set the value token (ref. #137)
> 
> Various linting errors fixed.
> 
> Fixes #136

Thank you 🙌 

Apologies, I forgot to mention similar change is required for `redeem`. 
Do you prefer this PR or separate ticket for this?

**Comment by gulshanvasnani** [comment]
@schemar,could you also extend returning `nonce` and `messageHash` to `redeem`.

**Comment by schemar** [comment]
> @schemar,could also extend returning `nonce` and `messageHash` to `redeem`.

Yes, yes, I am working on it 😊 
It's just that the transaction always reverts for the redeem integration test and I have a hard time figuring out where exactly it reverts. Any idea @sarvesh-ost ?

**Comment by 0xsarvesh** [comment]
@schemar do you know the reason for the failure? 

You could use 

debug.traceTransaction(transactionHash)

This will show solidity error message.

**Comment by schemar** [comment]
@sarvesh-ost @gulshanvasnani please have a look.

Added return parameters to Facilitator::redeem()

I added the return parameters the same way as for stake.
I added a unit test that should assert that it works.

On the CoGateway contract interact, I added a check so that the amount
is always greater than gas price times gas limit. I added an
accompanying unit test for that.

I gave up on an integration test and thus I don't know if my change
actually works. I could not do an integration test for multiple reasons:

1. Overall, the integration tests are written in a hardly readable way.
2. I could not redeem, because:
  * There is no UtilityToken set up, only OSTPrime.
  * There is no minted UtilityToken to redeem on auxiliary (could not mint due to 3.)
  * I could not redeem as the chainOwner from OSTPrime (not sure why not)
3. I could not progress the stake to redeem again, as our test nodes don't support getting the proof.
4. Our test nodes do not support `debug` to attach and debug transaction failure.

So, we should test it with JLP once it is released. 
Also, the integration tests need a massive overhaul (ref. #142).

All-in-all I am **very** concerned with the code quality of mosaic.js.

**Review by benjaminbollen — APPROVED** [review]
LGTM

**Pull request merged**
