### PR TITLE
Publishing now runs npm install

### LINKED ISSUE #70: Use prepack instead of prepare
NPM scripts should use `prepack` instead of `prepare` for the build steps.
For more info see [npm-scripts docs](https://docs.npmjs.com/misc/scripts)

### LINKED ISSUE #133: npm install must run when publishing
Currently, when publishing with npm, old mosaic-contract binaries are bundled if you don't run `npm install` before publishing.

### PR DESCRIPTION
**Pull request by schemar**
Changed prepare to prepack to only run when packaging (and before
publishing).

`npm install` is now run first as part of the `prepack` script.

Fixes #133 and fixes #70

### CODE REVIEW

**Review by hobofan — COMMENTED** [review]
LGTM 💯

**Review by 0xsarvesh — APPROVED** [review]
LGTM 🚀 

Did we agree on any kind of testing for this?

**Comment by schemar** [comment]
> LGTM 🚀
> 
> Did we agree on any kind of testing for this?

We didn't. Do you have an idea what kind of test I could add?

**Comment by schemar** [comment]
@sarvesh-ost do you have specific tests in mind?
I also updated the PR to include `package.json` updates to adhere to the dev guidelines. Please check. You may need to delete your pre-commit hook manually after updating.

**Comment by 0xsarvesh** [comment]
> @sarvesh-ost do you have specific tests in mind?
> I also updated the PR to include `package.json` updates to adhere to the dev guidelines. Please check. You may need to delete your pre-commit hook manually after updating.

Two ideas 
1. Take mosaic-contracts and compare bins from mosaic.js and mosaic.contracts. 
2. Actually, deploy contract, then do `eth.getCode` and compare with mosaic-contract bin. 

But this might be too much for this PR. We can discuss approaches separately.

**Pull request merged**
